#!/usr/bin/env bash

set -e

# Configure
_servers="localhost raspberrypi"
_ports="/dev/ttyACM0 /dev/tty.usbmodem14611 /dev/tty.usbmodem14241"

_name=development
_baud=115200
# All=128, Fatal=1, Error=2, Warning=3, Info=4, Debug=5, Operation = -1, None = -128
_trace=128


if [ ! -z "$1" ] && [[ "$1" == "--program" ]]; then
#  ssh $_server "screen -X -S $(lsof | grep $_port | awk '{print $2}') quit || true"
  for server in $_servers;
  do
    echo "$server"
    scp -r -q /tmp/$_name.* $server:/tmp/ || true
    for port in $_ports;
    do
      echo "$port"
      ssh $server "avrdude -F -D -c stk500v2 -p m2560 -b $_baud -P $port -U flash:w:/tmp/$_name.hex -U eeprom:w:/tmp/$_name.eep" || true
      ssh $server "/usr/local/bin/avrdude -F -D -c stk500v2 -p m2560 -b $_baud -P $port -U flash:w:/tmp/$_name.hex -U eeprom:w:/tmp/$_name.eep" || true
    done
  done
elif [ ! -z "$1" ] && [[ "$1" == "--screen" ]]; then
  screen $_port $_baud
else
  make clean && make BOARD=arduino_mega MODEL=atmega2560 FREQUENCY=16000000 NAME=$_name TRACE=$_trace
fi
