#!/usr/bin/env bash
set -e

### Configure ###
_commands=$@

_server="localhost"
if [ ! -z "$1" ]; then
  _server="$1"
fi

_port="/dev/ttyACM0"
if [ ! -z "$2" ]; then
  _port="$2"
fi

_name=program
_baud=115200
# All=128, Fatal=1, Error=2, Warning=3, Info=4, Debug=5, Operation = -1, None = -128
_trace=128

### Operations ###
if [[ "$_commands" == *"--program"* ]]; then
  echo "$_server"
  if [[ "$_server" == *"localhost"* ]]; then
    echo ""
  else
    scp -r -q $_name.* $_server:/tmp/
  fi

  echo "$_port"
  if [[ "$_server" == *"localhost"* ]]; then
    avrdude -F -D -c stk500v2 -p m2560 -b $_baud -P $_port -U flash:w:$_name.hex -U eeprom:w:$_name.eep
  else
    ssh $_server "avrdude -F -D -c stk500v2 -p m2560 -b $_baud -P $_port -U flash:w:/tmp/$_name.hex -U eeprom:w:/tmp/$_name.eep"
  fi
elif [[ "$_commands" == *"--screen"* ]]; then
  screen $_port $_baud
else
  make clean && make BOARD=arduino_mega MODEL=atmega2560 FREQUENCY=16000000 NAME=$_name TRACE=$_trace
fi
