#!/usr/bin/env bash

set -e

# Configure
_server=raspberrypi
_port=/dev/ttyACM0

_name=development
_baud=115200
# All=128, Fatal=1, Error=2, Warning=3, Info=4, Debug=5, Operation = -1, None = -128
_trace=128

if [ ! -z "$1" ] && [[ "$1" == "--program" ]]; then
  scp -r -q $(pwd)/$_name.* $_server:/tmp/
#  ssh $_server "screen -X -S $(lsof | grep $_port | awk '{print $2}') quit || true"
  ssh $_server "avrdude -F -D -c stk500v2 -p m2560 -b $_baud -P $_port -U flash:w:/tmp/$_name.hex -U eeprom:w:/tmp/$_name.eep"
elif [ ! -z "$1" ] && [[ "$1" == "--screen" ]]; then
  screen $_port $_baud
else
  make clean && make BOARD=arduino_mega MODEL=atmega2560 FREQUENCY=16000000 NAME=$_name TRACE=$_trace
fi
